package com.kl3jvi.processor.util

import com.squareup.kotlinpoet.FileSpec


fun FileSpec.Builder.addTopComment() = apply {
    addFileComment("This class was generated by Kl3jvi Mapper Processor\n")
    addFileComment("Do not modify this class.\n")
    addFileComment("--------------------------------")
}